package org.suggs.aoc2024

import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.suggs.adventofcode.Grid
import org.suggs.adventofcode.Util.createGridFromFileContent
import org.suggs.aoc2024.Day07Laboratories.countSplitterEncountersFrom

class Day07LaboratoriesTest {

    @Test
    fun `counts the splitter encogit aunters - small`() {
        countSplitterEncountersFrom(smallGrid) shouldBe 21
    }

    @Test
    @Disabled
    fun `counts the splitter encounters - large`() {
        countSplitterEncountersFrom(largeGrid) shouldBe 2124
    }

    private val largeGrid = createGridFromFileContent("day07-input.txt")
    private val smallGrid = Grid(
        """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
............... """
    )
}